/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as myWalletSol from "./MyWallet.sol";
export type { myWalletSol };
import type * as otpSol from "./OTP.sol";
export type { otpSol };
import type * as verifierSol from "./verifier.sol";
export type { verifierSol };
export type { Greeter } from "./Greeter";
export type { MyWalletDeployer } from "./MyWalletDeployer";
export type { OTPFactory } from "./OTPFactory";
